# name: Cypress Tests with Dependency and Artifact Caching

on: 
  workflow_dispatch: 
    inputs: 
      logLevel:
        description: 'log level'
        required: true
        default: 'warning'
        type: choice
        options: 
          - info
          - warning
          - debug
      tags:
        description: 'test workflow dispatch'
        required: false
        type: boolean
      environment:
        description: 'selecct your test env'
        type: environment
        required: true

jobs:

  cypress-test:
    strategy:
      matrix:
        specs: [
          ./cypress/e2e/loginOnce.spec.cy.js,
          ./cypress/e2e/mulUrl1.spec.cy.js
        ]

    permissions:
      contents: read
      issues: write
      checks: write
    
    runs-on: ubantu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: run cypress test
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          build: npm run build
          publish-summary: true
          browser: chrome

# on: push

# name: Cypress Tests using Cypress Docker Image

# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     container:
#       image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
#       options: --user 1001
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           build: npm run build
#           start: npm start
#           browser: chrome

# jobs:
#   install:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Cypress install
#         uses: cypress-io/github-action@v6
#         with:
#           # Disable running of tests within install job
#           runTests: false
#           build: npm run build

#       - name: Save build folder
#         uses: actions/upload-artifact@v4
#         with:
#           name: build
#           if-no-files-found: error
#           path: build

#   cypress-run:
#     runs-on: ubuntu-22.04
#     needs: install
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v6

#       - name: Download the build folder
#         uses: actions/download-artifact@v4
#         with:
#           name: build
#           path: build

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           start: npm start
#           browser: chrome